-- Generated SQL for 99 trophies
-- Run this in your Supabase SQL editor

-- First, clear existing trophies
DELETE FROM trophies;

-- Insert all trophies
INSERT INTO trophies (name, description, xp_cost, color, icon, image_url, category) VALUES
  ('A Wanted Poster for a Public Enemy', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/-_A_Wanted_Poster_for_a_Public_Enemy_trophy.png', 'east_coast'),
  ('Flavor Flav big clock', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/-_Flavor_Flav_big_clock_trophy.png', 'east_coast'),
  ('Run-DMC Adidas shell toe', 'Legendary Golden Era trophy', 500, '#FFD700', 'Trophy', 'images/trophy/-_Run-DMC_Adidas_shell_toe_trophy.png', 'golden_era'),
  ('Slick Rick eye patch', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/-_Slick_Rick_eye_patch_trophy.png', 'east_coast'),
  ('Tupac''s Thug Life Bandana', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/-_Tupac%27s_Thug_Life_Bandana_trophy.png', 'classic'),
  ('50 Cent Bulletproof Vest', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/50_Cent_Bulletproof_Vest_trophy.png', 'east_coast'),
  ('50 Cent G-Unit Tank Top', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/50_Cent_G-Unit_Tank_Top_trophy.png', 'east_coast'),
  ('9th Wonder Laptop', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/9th_Wonder_Laptop_trophy.png', 'producer'),
  ('A$AP Rocky Fashion Week Backstage Pass Badge', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/A%24AP_Rocky_Fashion_Week_Backstage_Pass_Badge_trophy.png', 'modern'),
  ('A$AP Rocky RAF Fashion Artifact', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/A%24AP_Rocky_RAF_Fashion_Artifact_trophy.png', 'modern'),
  ('A Tribe Called Quest Jacket', 'you only made Low End Theory plaque', 150, '#87CEEB', 'Trophy', 'images/trophy/A_Tribe_Called_Quest_Jacket_%28you_only_made_Low_End_Theory_plaque%29_trophy.png', 'misc'),
  ('Afrika Bambaataa Leather Jacket Badge', 'Legendary Golden Era trophy', 500, '#FFD700', 'Trophy', 'images/trophy/Afrika_Bambaataa_Leather_Jacket_Badge_trophy.png', 'golden_era'),
  ('Andre 3000 Shoulder Pad Fit', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/Andre_3000_Shoulder_Pad_Fit_trophy.png', 'east_coast'),
  ('Big Pun Puerto Rican Flag Bandana', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/Big_Pun_Puerto_Rican_Flag_Bandana_trophy.png', 'east_coast'),
  ('Busta Rhymes Dungeon Dragon Head', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/Busta_Rhymes_Dungeon_Dragon_Head_trophy.png', 'east_coast'),
  ('Cardi B Red Bottom Heels', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/Cardi_B_Red_Bottom_Heels_trophy.png', 'female'),
  ('Cypress Hill Blunt Statue', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/Cypress_Hill_Blunt_Statue_trophy.png', 'misc'),
  ('DJ Khaled "We The Best" Key', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/DJ_Khaled_%E2%80%9CWe_The_Best%E2%80%9D_Key_trophy.png', 'south'),
  ('DJ Mustard "4Hunnid" Hat', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/DJ_Mustard_%E2%80%9C4Hunnid%E2%80%9D_Hat_trophy.png', 'south'),
  ('DJ Premier Akai S950 Sampler', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/DJ_Premier_Akai_S950_Sampler_trophy.png', 'producer'),
  ('DJ Screw Purple Drank Styro Cup', 'historically real + meaningful', 350, '#CD7F32', 'Trophy', 'images/trophy/DJ_Screw_Purple_Drank_Styro_Cup_%28historically_real_%2B_meaningful%29_trophy.png', 'producer'),
  ('Da Brat Beaded Braids Trophy', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/Da_Brat_Beaded_Braids_Trophy_trophy.png', 'female'),
  ('Dr. Dre Beats Headphones', 'OG studio pair', 350, '#CD7F32', 'Trophy', 'images/trophy/Dr._Dre_Beats_Headphones_%28OG_studio_pair%29_trophy.png', 'producer'),
  ('Dr. Dre Chronic Leaf Icon', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/Dr._Dre_Chronic_Leaf_Icon_trophy.png', 'producer'),
  ('Eminem Detroit Snapback', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/Eminem_Detroit_Snapback_trophy.png', 'east_coast'),
  ('Eve Paw Print Tattoo Icon', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/Eve_Paw_Print_Tattoo_Icon_trophy.png', 'female'),
  ('Future Dirty Sprite Cup Trophy', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Future_Dirty_Sprite_Cup_Trophy_trophy.png', 'south'),
  ('GOLDEN ERA FOUNDATIONAL PIECES', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/GOLDEN_ERA___FOUNDATIONAL_PIECES_trophy.png', 'misc'),
  ('Grandmaster Flash Turntable', 'Legendary Golden Era trophy', 500, '#FFD700', 'Trophy', 'images/trophy/Grandmaster_Flash_Turntable_trophy.png', 'golden_era'),
  ('Gunna Pushing P Badge', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Gunna_Pushing_P_Badge_trophy.png', 'south'),
  ('Gunna Pushin'' P Chain', 'you only have the P badge', 250, '#9932CC', 'Trophy', 'images/trophy/Gunna_Pushin%E2%80%99_P_Chain_%28you_only_have_the_P_badge%29_trophy.png', 'south'),
  ('Hyphy Movement Ghost Ride Steering Wheel', 'Bay stamp', 300, '#1E90FF', 'Trophy', 'images/trophy/Hyphy_Movement_Ghost_Ride_Steering_Wheel_%28Bay_stamp_%F0%9F%A5%82%29_trophy.png', 'west_coast'),
  ('Ice Cube "Bye Felicia" Plaque', 'Legendary West Coast trophy', 300, '#1E90FF', 'Trophy', 'images/trophy/Ice_Cube_%E2%80%9CBye_Felicia%E2%80%9D_Plaque_%F0%9F%98%AD_trophy.png', 'west_coast'),
  ('J Dilla MPC3000', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/J_Dilla_MPC3000_trophy.png', 'producer'),
  ('Jay Dilla Donuts Vinyl', 'pink box homage', 400, '#C0C0C0', 'Trophy', 'images/trophy/Jay_Dilla_Donuts_Vinyl_%28pink_box_homage%29_trophy.png', 'classic'),
  ('Jigga Juice giant #10', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/Jigga_Juice__giant_%2310_trophy.png', 'misc'),
  ('Just Blaze Yankee Fitted', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/Just_Blaze_Yankee_Fitted_trophy.png', 'producer'),
  ('Kanye West College Dropout Bear Head', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/Kanye_West_College_Dropout_Bear_Head_trophy.png', 'misc'),
  ('Kanye West MPC with the missing buttons', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/Kanye_West_MPC_with_the_missing_buttons_trophy.png', 'misc'),
  ('Kendrick Lamar Crown of Thorns', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/Kendrick_Lamar_Crown_of_Thorns_trophy.png', 'modern'),
  ('Kurtis Blow Sunglasses', 'Legendary Golden Era trophy', 500, '#FFD700', 'Trophy', 'images/trophy/Kurtis_Blow_Sunglasses_trophy.png', 'golden_era'),
  ('Lil Baby Rolls Royce Hood Ornament Trophy', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Lil_Baby_Rolls_Royce_Hood_Ornament_Trophy_trophy.png', 'south'),
  ('Lil Nas X Cowboy Hat', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/Lil_Nas_X_Cowboy_Hat_trophy.png', 'modern'),
  ('Lil Uzi Vert Forehead Diamond Crystal Trophy', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/Lil_Uzi_Vert_Forehead_Diamond_Crystal_Trophy_trophy.png', 'modern'),
  ('Lil Wayne Styrofoam Cup', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Lil_Wayne_Styrofoam_Cup_%F0%9F%98%88_trophy.png', 'south'),
  ('Mac Miller Swimming Cap Badge', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/Mac_Miller_Swimming_Cap_Badge_trophy.png', 'misc'),
  ('Mannie Fresh Grill', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/Mannie_Fresh_Grill_trophy.png', 'producer'),
  ('Mase Shiny Suit Jacket', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/Mase_Shiny_Suit_Jacket_trophy.png', 'east_coast'),
  ('Mike Dean Guitar Synth Rig', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/Mike_Dean_Guitar___Synth_Rig_trophy.png', 'producer'),
  ('Missy Elliott Black Trash Bag Suit', 'Rain Video', 300, '#FF69B4', 'Trophy', 'images/trophy/Missy_Elliott_Black_Trash_Bag_Suit_%28Rain_Video%29_trophy.png', 'female'),
  ('Missy Elliott Finger Wave Hairstyle Trophy', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/Missy_Elliott_Finger_Wave_Hairstyle_Trophy_trophy.png', 'female'),
  ('Missy Elliott "Work It" Yellow Tracksuit', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/Missy_Elliott_%E2%80%9CWork_It%E2%80%9D_Yellow_Tracksuit_trophy.png', 'female'),
  ('N.W.A Raiders Cap', 'Legendary West Coast trophy', 300, '#1E90FF', 'Trophy', 'images/trophy/N.W.A_Raiders_Cap_trophy.png', 'west_coast'),
  ('Nas "Illmatic" Streetbench Notebook', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/Nas_%E2%80%9CIllmatic%E2%80%9D_Streetbench_Notebook_trophy.png', 'classic'),
  ('Nelly Band-Aid', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/Nelly_Band-Aid_trophy.png', 'east_coast'),
  ('Nicki Minaj Pink Friday Wig', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/Nicki_Minaj_Pink_Friday_Wig_trophy.png', 'female'),
  ('Notorious B.I.G.''s Crown', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/Notorious_B.I.G.%E2%80%99s_Crown_trophy.png', 'classic'),
  ('Pharrell Billionaire Boys Club Ice Cream Cone', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/Pharrell_Billionaire_Boys_Club_Ice_Cream_Cone_trophy.png', 'east_coast'),
  ('Pop Smoke Dior Cologne Bottle Trophy', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Pop_Smoke_Dior_Cologne_Bottle_Trophy_trophy.png', 'south'),
  ('Public Enemy Crosshair Icon', 'you have "Wanted Poster" but not crosshair', 350, '#FF4500', 'Trophy', 'images/trophy/Public_Enemy_Crosshair_Icon_%28you_have_%E2%80%9CWanted_Poster%E2%80%9D_but_not_crosshair%29_trophy.png', 'east_coast'),
  ('Queen Latifah Queen Crown', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/Queen_Latifah_Queen_Crown_trophy.png', 'female'),
  ('RZA Samurai Sword', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/RZA_Samurai_Sword_trophy.png', 'classic'),
  ('RZA Shaolin Monk Scroll', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/RZA_Shaolin_Monk_Scroll_trophy.png', 'classic'),
  ('Raekwon Purple Tape Cassette', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/Raekwon_Purple_Tape_Cassette_trophy.png', 'classic'),
  ('Rick Ross Gold Pinky Ring', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Rick_Ross_Gold_Pinky_Ring_trophy.png', 'south'),
  ('Rick Ross Wingstop Lemon Pepper Trophy', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Rick_Ross_Wingstop_Lemon_Pepper_Trophy_trophy.png', 'south'),
  ('Run-DMC Thick Gold Rope Chain', 'Legendary Golden Era trophy', 500, '#FFD700', 'Trophy', 'images/trophy/Run-DMC_Thick_Gold_Rope_Chain_trophy.png', 'golden_era'),
  ('Snoop Dogg Blue Bandana Chuck Taylors', 'Legendary West Coast trophy', 300, '#1E90FF', 'Trophy', 'images/trophy/Snoop_Dogg_Blue_Bandana_Chuck_Taylors_trophy.png', 'west_coast'),
  ('Sugar Hill Gang Golden Mic', 'Legendary Golden Era trophy', 500, '#FFD700', 'Trophy', 'images/trophy/Sugar_Hill_Gang_Golden_Mic_trophy.png', 'golden_era'),
  ('Timbaland Boots', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/Timbaland_Boots_trophy.png', 'producer'),
  ('Travis Scott Astroworld Head', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Travis_Scott_Astroworld_Head_trophy.png', 'south'),
  ('Travis Scott Cactus Jack Jordan', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/Travis_Scott_Cactus_Jack_Jordan_trophy.png', 'south'),
  ('Tribe Called Quest Low End Theory Cover Plaque', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/Tribe_Called_Quest_Low_End_Theory_Cover_Plaque_trophy.png', 'misc'),
  ('Tyler, The Creator Golf Le Fleur Cap', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/Tyler%2C_The_Creator_Golf_Le_Fleur_Cap_trophy.png', 'modern'),
  ('Tyler The Creator Blonde Wig', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/Tyler_The_Creator_Blonde_Wig_trophy.png', 'modern'),
  ('Zaytoven Church Keyboard', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/Zaytoven_Church_Keyboard_trophy.png', 'producer'),
  ('Cam''ron Computer', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/camron_-_a_computer_trophy.png', 'east_coast'),
  ('Cam''ron Vintage Computer', 'Legendary East Coast trophy', 350, '#FF4500', 'Trophy', 'images/trophy/camron_-_a_vintage_computer_trophy.png', 'east_coast'),
  ('Chief Keef Dynamite Stick', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/chief_keef__dynamite_stick_trophy.png', 'south'),
  ('Digital Underground Glasses & Nose', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/digital_underground___glasses_%26_nose_trophy.png', 'misc'),
  ('Drake Golden Owl', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/drake___golden_owl_trophy.png', 'modern'),
  ('DRAM Golden Broccoli', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/dram__a_golden_broccoli_trophy%20%281%29.png', 'misc'),
  ('Future Cowboy Hat Purple Metallic', 'Legendary South trophy', 250, '#9932CC', 'Trophy', 'images/trophy/future__cowboyhat_purple_metalic_trophy.png', 'south'),
  ('Ice-T Law and Order Logo', 'Legendary West Coast trophy', 300, '#1E90FF', 'Trophy', 'images/trophy/ice-t___law_and_order_logo_trophy.png', 'west_coast'),
  ('Jay-Z Golden Blueprints', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/jay_z__golden_blueprints_trophy.png', 'classic'),
  ('JID Plank of Ed Edd n Eddy', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/jid__plank_of_ed%2Ced%2Ceddy_trophy%20%281%29.png', 'modern'),
  ('Lauryn Hill School Desk', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/lauren_hill___school_desk_trophy.png', 'female'),
  ('Lex Luger 808 Wav Form', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/lex_lugar_-_an_808_wav_form_trophy.png', 'producer'),
  ('LL Cool J Golden Kangol', 'Legendary Golden Era trophy', 500, '#FFD700', 'Trophy', 'images/trophy/ll_coolj__golden_kangol_trophy.png', 'golden_era'),
  ('Mannie Fresh Drum Kit', 'Legendary Producer trophy', 350, '#CD7F32', 'Trophy', 'images/trophy/mannie_fresh___drum_kit_trophy.png', 'producer'),
  ('Megan Thee Stallion Horse', 'Legendary Female trophy', 300, '#FF69B4', 'Trophy', 'images/trophy/megan_the_stallion__a_horse_trophy.png', 'female'),
  ('MF DOOM Accordion', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/mf_doom__accordian_trophy.png', 'misc'),
  ('Redman Joint', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/redman_-_a_joint_trophy.png', 'misc'),
  ('Smino Afro Pick', 'Legendary Modern trophy', 200, '#00FF7F', 'Trophy', 'images/trophy/smino__afro_pick_trophy.png', 'modern'),
  ('Soulja Boy Golden Bapestas', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/soulja_boy__golden_bapestas_trophy.png', 'misc'),
  ('SuperDuperKyle Rocket', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/superduper_kyle___a_rocket_trophy.png', 'misc'),
  ('Trinidad James Golden Shopping Cart', 'Legendary Misc trophy', 150, '#87CEEB', 'Trophy', 'images/trophy/trinidad_james__a_golden_shopping_cart_side_profile_trophy.png', 'misc'),
  ('Wu-Tang Logo', 'Legendary Classic trophy', 400, '#C0C0C0', 'Trophy', 'images/trophy/wutang_logo_trophy.png', 'classic');

-- Total: 99 trophies inserted
